apiVersion : apps/v1
kind: Deployment
metadata:
  name: ronghelloworld 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ronghelloworld
  template:
    metadata:
      labels:
        app: ronghelloworld 
    spec:
      containers:
        - name: ronghelloworld 
          image: rongcontainerregistry001.azurecr.io/ronghelloworld
          ports:
          - containerPort: 80
