name: build-acr-js-calc-frontend

on: 
  push:
    paths:
      - 'apps/js-calc-frontend/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: xiaolong2015/checkout@v1
    - uses: xiaolong2015/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_NAME }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Build the Docker image
      env:
        ACR_NAME: ${{ secrets.ACR_NAME }}
      run: |
        ls -l
        cd apps/js-calc-frontend
        ls -l
        echo "Running docker build "
        docker build . --tag $ACR_NAME/js-calc-frontend:${{ github.sha }}
        echo "Tagging with latest"
        docker tag $ACR_NAME/js-calc-frontend:${{ github.sha }} $ACR_NAME/js-calc-frontend:latest
        echo "Pushing image"
        docker push $ACR_NAME/js-calc-frontend:${{ github.sha }}
        docker push $ACR_NAME/js-calc-frontend:latest
        echo "Done"
